### ISSUE TITLE
Jenkins doesn't run database migration script

### ISSUE THREAD

**Issue by wilsonge** [joomla/statistics-server#45]
It currently runs the update script but not `php bin/stats database:migrate` - assuming it should but to check before I make changes. Ran manually in terminal for now. Presumably related to https://github.com/joomla/statistics-server/issues/36

**Comment by mbabker** [comment]
I’d leave it out just because things don’t parse the SQL files well (PDO doesn’t like the delimiters or something, I forget what).

**Comment by wilsonge** [comment]
If we're leaving it out then we may as well keep the triggers in if we're just going to manually run the things through phpmyadmin?

**Comment by mbabker** [comment]
Can't, then you catastrophically break the testing setup.

**Comment by mbabker** [comment]
(Or, you end up with a lot of copies of the SQL schema floating around and the test environment doesn't work with any of the production resources, which kind of defeats the purpose)

**Comment by wilsonge** [comment]
OK I'll just document it https://github.com/joomla/statistics-server/pull/46 - if you could review and add anything i'm missing
